language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

after_success:
  - npm run coverage:upload
  - npm run semantic-release
