name: Browser test

on: [pull_request]

jobs:
  browser_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run start-fixtures-server &
      - run: sleep 3 # give server some time to start
      - run: npm run test:browser
