name: node_modules folder size

on: [pull_request]

jobs:
  folder_size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install --production
      - run: npx get-folder-size --folder=node_modules/ | grep "^[012]\."
